name: Deploy Express API to Azure Web App

on:
  push:
    branches: ["main"]

env:
  AZURE_WEBAPP_NAME: "akshara-vanam-api" # replace with your Azure Web App name
  NODE_VERSION: "20.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: editor-service/package-lock.json

      - name: Install dependencies
        working-directory: ./editor-service
        run: npm install

      - name: Build app
        working-directory: ./editor-service
        run: npm run build

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./editor-service
